name: GitHub to Slack Integration

on: [push]

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Send Slack notification
        uses: rtCamp/github-slack@v3
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
